# try:
#     # x=5
#     print(x)
# except:
#     print("error is there")    
# try:
#     print(x)
# except NameError:
#     print("print variable)")    
# except:
#     print("normal error is there")
# try:
#     print(x)
# except:
#     print("error is there")
# else:
#     print("there is no error") 
# finally:
    # print("sucessfully completed")       
# x=int(input("a postive no."))
# if x<0:
#     raise Exception("its not a positive no.")
# else:
#     print(x)


